services:
  # ğŸŒ ConfiguraciÃ³n del servidor web
  - type: web
    name: findata  
    env: python
    buildCommand: "pip install -r requirements.txt"  # Instala dependencias
    startCommand: "gunicorn run:app"  # Inicia el servidor
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0  # Cambia si usas otra versiÃ³n de Python
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true  # Render genera una clave secreta automÃ¡ticamente

databases:
  # ğŸ—„ï¸ ConfiguraciÃ³n de PostgreSQL
  - name: findata-db
    databaseName: findata
    user: findata_user